baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'hugo-theme-codex'

[params]
  twitter = "https://twitter.com/CaptainThomThom"
  github = "https://github.com/thompson-pilot"
